version: '3'
 
services:
  pyms:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    depends_on:
      - proxy
      - db
    links:
      - proxy
      - db
    expose:
      - "5000"
    ports:
      - "${SERVER_EXPOSED_PORT}:${SERVER_PORT}"
    environment:
      TZ: "America/Santiago"
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_EXPOSED_PORT: ${SERVER_EXPOSED_PORT}
      SERVER_URL: ${SERVER_URL}
      SERVER_DEBUG: ${SERVER_DEBUG}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    container_name: pyms-proxy
    ports:
      - "${NGINX_EXPOSED_PORT}:${NGINX_PORT}"
  db:
    image: postgres:12.0-alpine
    container_name: pyms-db
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "America/Santiago"